#!/usr/bin/env node
console.log(process.argv)
const exec = require('child_process').exec;

const child = exec('ls ' + process.argv[2], function (err, stdout, stderr) {
	if(err) {
		console.log(err)
	}
	console.log(stdout)

})
