#!/usr/bin/env node
// console.log(process.argv)
// 引入模块
const exec = require('child_process').exec;
const program = require('commander')
const figlet = require('figlet');
const levelup = require('levelup')
const leveldown = require('leveldown')

const VERSION = '0.1.0';
figlet('easy-open', function(err, data) {
	if (err) {
			console.log('Something went wrong...');
			console.dir(err);
			return;
	}
	console.log(data)
});
// show available commands
program
  .command('exec <sortName> <originSite>')
  .alias('ex')
  .description('execute the given remote cmd')
  .option("-e, --exec_mode <mode>", "Which exec mode to use")
  .action(function(sortName, originSite){
    console.log('exec "%s" using %s mode', sortName, originSite);
  }).on('--help', function() {
    console.log('  Examples:');
    console.log();
    console.log('    $ deploy exec sequential');
    console.log('    $ deploy exec async');
    console.log();
  });

program.parse(process.argv);
if(program.args.length === 0) {
	program.help();
}
if(program.add) {
	console.log('add', program.args);
	
}
// 1) Create our store
const db = levelup(leveldown('./mydb'))
// 3) Fetch by key
db.get('name', function (err, value) {
	if (err) return console.log('Ooops!', err) // likely the key was not found

	// Ta da!
	console.log('name=' + value)
})
// // 2) Put a key & value
// db.put('name', 'levelup', function (err) {
//   if (err) return console.log('Ooops!', err) // some kind of I/O error

//   // 3) Fetch by key
//   db.get('name', function (err, value) {
//     if (err) return console.log('Ooops!', err) // likely the key was not found

//     // Ta da!
//     console.log('name=' + value)
//   })
// })

